"""Qwen-7B Packaging Field Extractor.

This script takes the JSON payload generated by `predict_yolo.py` and sends it to
Qwen-7B (supports Ollama, vLLM / LM Studio / OpenAI-compatible endpoint, or prints the ready prompt).

Usage:
  # 1. Print formatted prompt / payload:
  python scripts/qwen_extract.py --payload runs/predict/qwen_payload_sample.json

  # 2. If running Ollama locally:
  python scripts/qwen_extract.py --payload runs/predict/qwen_payload_sample.json --backend ollama --model qwen2.5:7b
"""

import argparse
import json
from pathlib import Path
import base64
import urllib.request
import urllib.error
from typing import Iterable, Optional

def call_ollama(
    prompt: str,
    model: str = "qwen2.5:7b",
    endpoint: str = "http://localhost:11434/api/generate",
    image_paths: Optional[Iterable[str]] = None,
) -> str:
    """Call a local Ollama Qwen model, optionally with image frames.

    Ollama's generate API expects base64-encoded images.  Supplying images is
    supported by vision-capable tags such as ``qwen2.5vl:7b``; text-only Qwen
    tags continue to work when ``image_paths`` is omitted.
    """
    payload = {
        "model": model,
        "prompt": prompt,
        "stream": False,
        "format": "json",
        "options": {"temperature": 0, "num_predict": 2048, "num_ctx": 16384},
    }
    images = []
    for image_path in image_paths or []:
        path = Path(image_path)
        if path.is_file():
            images.append(base64.b64encode(path.read_bytes()).decode("ascii"))
    if images:
        payload["images"] = images
    req = urllib.request.Request(
        endpoint,
        data=json.dumps(payload).encode("utf-8"),
        headers={"Content-Type": "application/json"}
    )
    try:
        with urllib.request.urlopen(req, timeout=120) as response:
            res = json.loads(response.read().decode("utf-8"))
            return res.get("response", "")
    except urllib.error.URLError as e:
        return f"[-] Ollama connection error: {e}. Ensure Ollama is running (`ollama serve`)."

def main():
    parser = argparse.ArgumentParser(description="Extract Packaging Fields using Qwen-7B")
    parser.add_argument("--payload", type=str, required=True, help="Path to qwen_payload_*.json")
    parser.add_argument("--backend", type=str, default="print", choices=["print", "ollama"], help="Inference backend")
    parser.add_argument("--model", type=str, default="qwen2.5:7b", help="Qwen model tag")
    parser.add_argument("--endpoint", type=str, default="http://localhost:11434/api/generate", help="API URL")

    args = parser.parse_args()
    p_path = Path(args.payload)
    if not p_path.is_file():
        print(f"[-] Payload file not found: {args.payload}")
        return

    with open(p_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    prompt = data.get("qwen_7b_prompt", "")

    if args.backend == "ollama":
        print(f"[+] Sending prompt to Ollama model '{args.model}'...")
        out = call_ollama(prompt, args.model, args.endpoint)
        print("\n" + "="*50)
        print("QWEN-7B EXTRACTED PACKAGING FIELDS (JSON):")
        print("="*50)
        print(out)
    else:
        print("\n" + "="*60)
        print("READY-TO-USE QWEN-7B PROMPT:")
        print("="*60)
        print(prompt)
        print("="*60)
        print("[Tip]: Run with `--backend ollama` if you have Ollama running with Qwen2.5-7B.")

if __name__ == "__main__":
    main()
